---

- name: config tors
  hosts: localhost
  gather_facts: true

  tasks:
  
    - name: Creates directory
      file:
        path: "{{ item }}"
        state: directory
#       become: true
#       become_method: sudo
#       become_user: "{{ account }}"
      with_items:
      - {{ home }}/.aws
      - {{ home }}/.evalai
  
    - name: aws config
      shell: 'echo "[default] \nregion=us-east-1\naws_access_key_id = {{ aws_access_key_id }}\naws_secret_access_key = {{ aws_secret_access_key }}" > {{ home }}/.aws/config'

    - name: evalai config
      shell: 'echo "{\"auth_token\": \"{{ auth_token }}\",\n\"evalai_api_server\": \"https://eval.ai\",\n\"queue_name\": \"{{ queue_name }}\",\n\"challenge_pk\": \"{{ challenge_pk }}\"}" > {{ home }}/.evalai/worker_config.json'
