
---

- name: run script from git repo
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Clone git repo
      ansible.builtin.git:
        repo: "{{ repo }}"
        dest: "/opt/git-repo"
      environment:
        GIT_TERMINAL_PROMPT: 0 # reports "terminal prompts disabled" on missing password

    - name: Run script
      shell: "source /opt/git-repo/{{ script }}"
